[tool.poetry]
name = "dining_philosophers"
version = "0.1.0"
description = ""
authors = ["Lievi Silva <lievi.silva@luizalabs.com>"]

[tool.poetry.dependencies]
python = "^3.9"
mock = "^4.0.2"
coverage = "^5.3"
pytest-cov = "^2.10.1"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
black = "^20.8b1"
mypy = "^0.790"
bandit = "^1.6.2"
flake8 = "^3.8.3"
ipython = "^7.18.1"

[build-system]
requires = ["poetry>=1.1.4"]
build-backend = "poetry.masonry.api"
